# LM Studio Configuration
lm_api_url: "http://localhost:1234/v1"
model_name: "mistralai/mistral-7b-instruct-v0.3"
embed_model_name: "intfloat/e5-small"
data_file: "GreenAirChatBot/airdatafiles3.txt"
collection_name: "greenair_collection"
