FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY config.docker.yml config.yml


CMD ["python", "chatbot2.py"]

#CMD ["tail", "-f", "/dev/null"]