FROM python:3.12-slim

WORKDIR /app
RUN apt-get update && apt-get install -y curl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
COPY config.docker.yml config.yml

RUN chmod +x run.sh

CMD ["./run.sh"]
